language: cpp

matrix:
    include:
        - os: linux
          sudo: required
          dist: trusty
          compiler: gcc
          env:
            - CMAKE_BUILD_TYPE=Debug
            - BUILD_COVERAGE="OFF"
        - os: linux
          sudo: required
          dist: trusty
          compiler: gcc
          env:
            - CMAKE_BUILD_TYPE=Release
            - BUILD_COVERAGE="ON"
        - os: osx
          compiler: clang
          env:
            - CMAKE_BUILD_TYPE=Debug
            - BUILD_COVERAGE="OFF"
        - os: osx
          compiler: clang
          env:
            - CMAKE_BUILD_TYPE=Release
            - BUILD_COVERAGE="OFF"

install:
    - source scripts/travis-install.sh

script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -DENABLE_COVERAGE=$BUILD_COVERAGE ..
  - cmake --build .
  - ctest -V
  - if [ BUILD_COVERAGE == "ON" ]
      coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info.cleaned # uploads to coveralls
    fi
