language: cpp

matrix:
    include:
        - os: linux
          sudo: required
          dist: trusty
          compiler: gcc
          env: CMAKE_BUILD_TYPE=Debug ENABLE_COVERAGE=ON
        - os: linux
          sudo: required
          dist: trusty
          compiler: gcc
          env: CMAKE_BUILD_TYPE=Release ENABLE_COVERAGE=OFF
        - os: osx
          compiler: clang
          env: CMAKE_BUILD_TYPE=Debug ENABLE_COVERAGE=OFF
        - os: osx
          compiler: clang
          env: CMAKE_BUILD_TYPE=Release ENABLE_COVERAGE=OFF

install:
    - source scripts/travis-install.sh

script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -DENABLE_COVERAGE=$ENABLE_COVERAGE ..
  - cmake --build .
  - ctest -V

after_script:
  - if [[ $ENABLE_COVERAGE == 'ON' ]]; then
      make coverage;
      coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info.cleaned;
    fi