version: "0.1.0.{build}"
os: Visual Studio 2015

platform:
  - x64

configuration:
  - Release

init:
  - cmake --version
  - msbuild /version

clone_folder: C:\projects\hackedit

branches:
  except:
    - gh-pages

install:
  - set QTDIR=C:\Qt\5.7\msvc2015_64
  - set PATH=%PATH%;%QTDIR%\bin;%QTDIR%\lib
  - set CMAKE_PREFIX_PATH=%QTDIR%
  - set GTEST_COLOR=1

build_script:
  - cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=TRUE .
  - cmake --build . --config Release

test_script:
  - Publish\bin\HackEdit.Common.Logging.Tests.exe
  - Publish\bin\HackEdit.Editor.Backend.Tests.exe
